/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alelo.view;

import br.com.alelo.model.bean.Projects;
import br.com.alelo.model.dao.ProjectsDao;
import javax.swing.JOptionPane;

/**
 *
 * @author atomic
 */
public class ProjectsRegistration extends javax.swing.JFrame {

    /**
     * Creates new form ProjectsRegistration
     */
    public ProjectsRegistration() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        intFormCadastrarProjeto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnNovoProjeto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        intFormCadastrarProjeto = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtProjeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Dados Teste API");

        pnlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMenu.setName(""); // NOI18N
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNovoProjeto.setIcon(new javax.swing.ImageIcon("C:\\Users\\atomic\\Documents\\NetBeansProjects\\DataManagerApi\\icos\\newProject.png")); // NOI18N
        btnNovoProjeto.setToolTipText("Novo Projeto");
        btnNovoProjeto.setBorder(null);
        btnNovoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProjetoActionPerformed(evt);
            }
        });
        pnlMenu.add(btnNovoProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 60));

        jLabel4.setText("Novo Projeto");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 20));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        intFormCadastrarProjeto.setClosable(true);
        intFormCadastrarProjeto.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        intFormCadastrarProjeto.setTitle("Novo Projeto");
        intFormCadastrarProjeto.setVisible(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 102, 34));

        btnCadastrar2.setText("Cadastrar");
        btnCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 100, 34));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Projeto"));

        jLabel1.setText("Autor");

        jLabel2.setText("Projeto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtAutor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(txtProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 90));

        javax.swing.GroupLayout intFormCadastrarProjetoLayout = new javax.swing.GroupLayout(intFormCadastrarProjeto.getContentPane());
        intFormCadastrarProjeto.getContentPane().setLayout(intFormCadastrarProjetoLayout);
        intFormCadastrarProjetoLayout.setHorizontalGroup(
            intFormCadastrarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        intFormCadastrarProjetoLayout.setVerticalGroup(
            intFormCadastrarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intFormCadastrarProjetoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jDesktopPane1.add(intFormCadastrarProjeto);
        intFormCadastrarProjeto.setBounds(79, 82, 380, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        setBounds(0, 0, 858, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        txtAutor.setText("");
        txtProjeto.setText("");
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar2ActionPerformed
        
        Projects projects = new Projects();
        
        String author = txtAutor.getText();
        String projectName = txtProjeto.getText();
        
        if (!"".equals(author)) {
            projects.setAuthor(author);
        } else {
            JOptionPane.showMessageDialog(null, "O Campo Author deve ser prenchido!");
        }
        
        if (!"".equals(projectName)) {
            projects.setName(projectName);
        } else {
            JOptionPane.showMessageDialog(null, "O Campo Projeto deve ser prenchido!");
        }
        
        ProjectsDao projectsDao = new ProjectsDao();
        
        if (projectsDao.AddProject(projects)){
            intFormCadastrarProjeto.setVisible(false);
            //JOptionPane.showMessageDialog(null, "Projeto " + projectName + " foi criado com sucesso! " + projects.getId());  
            JOptionPane.showMessageDialog(null, "Projeto " + projectName + " foi criado com sucesso!");  
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar criar o projeto " + projectName);
        }
    }//GEN-LAST:event_btnCadastrar2ActionPerformed

    private void btnNovoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProjetoActionPerformed

        if(!intFormCadastrarProjeto.isVisible())
            intFormCadastrarProjeto.setVisible(true);
        
    }//GEN-LAST:event_btnNovoProjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectsRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectsRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectsRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectsRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectsRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar2;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovoProjeto;
    private javax.swing.JInternalFrame intFormCadastrarProjeto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtProjeto;
    // End of variables declaration//GEN-END:variables
}
